name: "Flatpak Qt6"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak Builder with Qt 6.8 and Poppler"
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.8
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build flatpak
      uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: BeamerPresenter.flatpak
        manifest-path: packaging/io.github.beamerpresenter.BeamerPresenter-qt6.yml
        arch: x86_64
        cache-key: flatpak-builder-${{ github.sha }}

    - name: Rename
      run: mv BeamerPresenter.flatpak BeamerPresenter-Qt6.flatpak

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          BeamerPresenter-Qt6.flatpak
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
