name: "Package for Ubuntu 22.04"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  MUPDF_VERSION: 1.27.2
  MUPDF_SHA256SUM: 35049dcd0b1a541be2cca1eb4bbd6b41a51e0ed44799333b7bde4528461e2848
  CMAKE_BUILD_PARALLEL_LEVEL: 4

jobs:
  generic:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { QT_VERSION_MAJOR: 5, BACKEND: mupdf }
          - { QT_VERSION_MAJOR: 5, BACKEND: poppler }
          - { QT_VERSION_MAJOR: 5, BACKEND: qtpdf }
          - { QT_VERSION_MAJOR: 6, BACKEND: mupdf }
    name: build+package Qt${{ matrix.QT_VERSION_MAJOR }} ${{ matrix.BACKEND }}
    env:
      QT_VERSION_MAJOR: ${{ matrix.QT_VERSION_MAJOR }}
      BACKEND: ${{ matrix.BACKEND }}
      PACKAGE: beamerpresenter-${{ matrix.BACKEND }}-qt${{ matrix.QT_VERSION_MAJOR}}-jammy-x86_64.deb

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Run build script
      run: |
        sudo apt-get update -y
        bash packaging/ubuntu2204.sh

    - name: Rename package
      run: |
        mv beamerpresenter-${{ matrix.BACKEND }}-qt${{ matrix.QT_VERSION_MAJOR}}-x86_64.deb ${{ env.PACKAGE }}

    - name: Archive package
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.PACKAGE }}
        path: ${{ env.PACKAGE }}

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ env.PACKAGE }}
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}


  mupdfsmall:
    runs-on: ubuntu-22.04
    name: build+package MuPDF small
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Download and unpack MuPDF
      run: |
        sudo apt-get update -y
        sudo apt install -y lunzip
        wget -q https://mupdf.com/downloads/archive/mupdf-${{ env.MUPDF_VERSION }}-source.tar.lz
        sha256sum -c - <<< "${{ env.MUPDF_SHA256SUM }} mupdf-${{ env.MUPDF_VERSION }}-source.tar.lz"
        tar -xf "mupdf-${{ env.MUPDF_VERSION }}-source.tar.lz"

    - name: Build MuPDF
      run : |
        sudo apt install -y make cmake g++ zlib1g-dev libfreetype-dev libharfbuzz-dev libjpeg-dev libopenjp2-7-dev libjbig2dec0-dev libgumbo-dev libmujs-dev freeglut3-dev libbrotli-dev
        cd "mupdf-${{ env.MUPDF_VERSION }}-source"
        rm -rf thirdparty/{freeglut,freetype,harfbuzz,jbig2dec,libjpeg,openjpeg,zlib}
        CFLAGS+=' -fPIC -ffat-lto-objects'
        CXXFLAGS+=' -fPIC'
        USE_SYSTEM_LIBS='yes'
        XCFLAGS+=' -DTOFU -DTOFU_CJK -DTOFU_SIL -DFZ_ENABLE_JS=0'
        export CFLAGS CXXFLAGS USE_SYSTEM_LIBS XCFLAGS
        make build=release libs

    - name: Configure with Qt5 + small MuPDF
      run: >
        sudo apt install -y qtmultimedia5-dev libqt5svg5-dev qttools5-dev;
        cmake
        -B build_qt5_mupdf_small
        -DUBUNTU_VERSION=22.04
        -DUSE_MUPDF=ON
        -DUSE_POPPLER=OFF
        -DUSE_QTPDF=OFF
        -DUSE_EXTERNAL_RENDERER=OFF
        -DLINK_MUJS=OFF
        -DLINK_GUMBO=ON
        -DMUPDF_LIB_PATH="$(pwd)/mupdf-${{ env.MUPDF_VERSION }}-source/build/release/libmupdf.a"
        -DMUPDF_THIRD_LIB_PATH="$(pwd)/mupdf-${{ env.MUPDF_VERSION }}-source/build/release/libmupdf-third.a"
        -DMUPDF_INCLUDE_DIR="$(pwd)/mupdf-${{ env.MUPDF_VERSION }}-source/include"
        -DUSE_TRANSLATIONS=ON
        -DQT_VERSION_MAJOR=5
        -DQT_VERSION_MINOR=15
        -DMARK_AS_SMALL=ON
        -DGIT_VERSION=OFF
        -DCMAKE_BUILD_TYPE='Release'
        -DCPACK_GENERATOR='DEB;'
        -DCMAKE_INSTALL_PREFIX='/usr'
        -DCMAKE_INSTALL_SYSCONFDIR='/etc'
        -DINSTALL_LICENSE=OFF

    - name: Build with Qt5 + small MuPDF
      run: cmake --build build_qt5_mupdf_small

    - name: Package with Qt5 + small MuPDF
      run: |
        cpack --config build_qt5_mupdf_small/CPackConfig.cmake
        mv beamerpresenter-mupdf-small-qt5-x86_64.deb beamerpresenter-mupdf-small-qt5-jammy-x86_64.deb

    - name: Archive package with Qt5 + small MuPDF
      uses: actions/upload-artifact@v7
      with:
        name: beamerpresenter-mupdf-small-qt5-jammy-x86_64.deb
        path: beamerpresenter-mupdf-small-qt5-jammy-x86_64.deb


    - name: Configure with Qt6 + small MuPDF
      run: >
        sudo apt install -y qt6-multimedia-dev libqt6svg6-dev qt6-tools-dev qt6-tools-dev-tools libqt6opengl6-dev libgl1-mesa-dev qt6-l10n-tools;
        cmake
        -B build_qt6_mupdf_small
        -DUBUNTU_VERSION=22.04
        -DUSE_MUPDF=ON
        -DUSE_POPPLER=OFF
        -DUSE_QTPDF=OFF
        -DUSE_EXTERNAL_RENDERER=OFF
        -DLINK_MUJS=OFF
        -DLINK_GUMBO=ON
        -DMUPDF_LIB_PATH="$(pwd)/mupdf-${{ env.MUPDF_VERSION }}-source/build/release/libmupdf.a"
        -DMUPDF_THIRD_LIB_PATH="$(pwd)/mupdf-${{ env.MUPDF_VERSION }}-source/build/release/libmupdf-third.a"
        -DMUPDF_INCLUDE_DIR="$(pwd)/mupdf-${{ env.MUPDF_VERSION }}-source/include"
        -DUSE_TRANSLATIONS=ON
        -DQT_VERSION_MAJOR=6
        -DQT_VERSION_MINOR=2
        -DMARK_AS_SMALL=ON
        -DGIT_VERSION=OFF
        -DCMAKE_BUILD_TYPE='Release'
        -DCPACK_GENERATOR='DEB;'
        -DCMAKE_INSTALL_PREFIX='/usr'
        -DCMAKE_INSTALL_SYSCONFDIR='/etc'
        -DINSTALL_LICENSE=OFF

    - name: Build with Qt6 + small MuPDF
      run: cmake --build build_qt6_mupdf_small

    - name: Package with Qt6 + small MuPDF
      run: |
        cpack --config build_qt6_mupdf_small/CPackConfig.cmake
        mv beamerpresenter-mupdf-small-qt6-x86_64.deb beamerpresenter-mupdf-small-qt6-jammy-x86_64.deb

    - name: Archive package with Qt6 + small MuPDF
      uses: actions/upload-artifact@v7
      with:
        name: beamerpresenter-mupdf-small-qt6-jammy-x86_64.deb
        path: beamerpresenter-mupdf-small-qt6-jammy-x86_64.deb


    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          beamerpresenter-mupdf-small-qt5-jammy-x86_64.deb
          beamerpresenter-mupdf-small-qt6-jammy-x86_64.deb
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
